/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 male.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/male.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['ASD-MMNN040-1910_STD_Regular'].geometry} material={materials.initialShadingGroup} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/male.glb')
